theme: jekyll-theme-cayman
menu_links:
  - title: Home
    url: index.html
  - title: Analysis
    url: analysis.html
  - title: Sources
    url: sources.html
  - title: About
    url: about.html
  

