title: Do You Really Know Your Colors
description: Psychology Experiment and Analysis
baseurl: "https://debaryasaha.github.io/psych_experiment/" 
theme: jekyll-theme-cayman
menu_links:
  - title: Home
    url: index.html
  - title: Analysis
    url: analysis.rmd
  - title: Sources
    url: sources.rmd
  - title: About
    url: about.html
  

